# Generated by Django 5.0.2 on 2024-04-01 15:27

import hospital.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Other',
            fields=[
                ('Patient_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=20)),
                ('DateofBirth', models.DateField()),
                ('gender', models.CharField(default=None, max_length=6)),
                ('Height', models.IntegerField()),
                ('Weight', models.IntegerField()),
                ('Next_of_kin', models.CharField(max_length=255)),
                ('Relationship', models.CharField(max_length=255)),
                ('contact_Next_of_kin', models.CharField(blank=True, max_length=13)),
                ('Marital_status', models.CharField(default=None, max_length=25)),
                ('Contact', models.CharField(blank=True, max_length=13)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('Residence', models.CharField(max_length=255)),
                ('current_medication', models.CharField(default=None, max_length=700)),
                ('reason_for_seeing_doctor', models.CharField(default=None, max_length=700)),
                ('Desease', models.CharField(default=None, max_length=500, null=True)),
                ('Doctors_comment', models.CharField(default=None, max_length=700, null=True)),
                ('Medication_given', models.CharField(default=None, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registered_Students',
            fields=[
                ('name', models.CharField(max_length=225)),
                ('Registration_number', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('Amount_Paid', models.IntegerField(default=1220000)),
                ('Balance', models.IntegerField(default=hospital.models.Registered_Students.balance)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('DateofBirth', models.DateField()),
                ('gender', models.CharField(default=None, max_length=6)),
                ('Height', models.IntegerField()),
                ('Weight', models.IntegerField()),
                ('Next_of_kin', models.CharField(max_length=255)),
                ('Relationship', models.CharField(max_length=255)),
                ('contact_Next_of_kin', models.CharField(blank=True, max_length=13)),
                ('Marital_status', models.CharField(default=None, max_length=25)),
                ('Contact', models.CharField(blank=True, max_length=13)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('Residence', models.CharField(max_length=255)),
                ('reason_for_seeing_doctor', models.CharField(default=None, max_length=700)),
                ('current_medication', models.CharField(default=None, max_length=700)),
                ('Desease', models.CharField(default=None, max_length=500, null=True)),
                ('Doctors_comment', models.CharField(default=None, max_length=700, null=True)),
                ('Medication_given', models.CharField(default=None, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Unique_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default=0, max_length=255)),
                ('DateofBirth', models.DateField(default=None, max_length=255)),
                ('Course', models.CharField(max_length=255)),
                ('Registration_number', models.CharField(default=None, max_length=255, unique=True)),
                ('gender', models.CharField(default=None, max_length=6)),
                ('Height', models.IntegerField(default=None)),
                ('Weight', models.IntegerField(default=None)),
                ('Next_of_kin', models.CharField(default=None, max_length=255)),
                ('contact_Next_of_kin', models.CharField(blank=True, default=None, max_length=13)),
                ('Relationship', models.CharField(default=None, max_length=255)),
                ('Marital_status', models.CharField(default=None, max_length=25)),
                ('Contact', models.CharField(blank=True, default=None, max_length=13)),
                ('email', models.EmailField(blank=True, default=None, max_length=254)),
                ('Residence', models.CharField(default=None, max_length=255)),
                ('current_medication', models.CharField(default=None, max_length=700, null=True)),
                ('reason_for_seeing_doctor', models.CharField(default=None, max_length=700)),
                ('Desease', models.CharField(default=None, max_length=500, null=True)),
                ('Doctors_comment', models.CharField(default=None, max_length=700, null=True)),
                ('Medication_given', models.CharField(default=None, max_length=500, null=True)),
            ],
        ),
    ]
