# Generated by Django 5.0.2 on 2024-04-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_staff_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered_students',
            name='Balance',
            field=models.IntegerField(),
        ),
    ]
