# Generated by Django 5.0.2 on 2024-04-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_registered_students_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='other',
            name='lab_comment',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='lab_comment',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='lab_comment',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='registered_students',
            name='Balance',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
