# Generated by Django 5.0.2 on 2024-04-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_other_lab_comment_staff_lab_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other',
            name='lab_comment',
            field=models.CharField(default=0, max_length=500, null=True),
        ),
    ]
