# Generated by Django 5.0.2 on 2024-04-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_alter_other_lab_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='lab_comment',
            field=models.CharField(default=0, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='lab_comment',
            field=models.CharField(default=0, max_length=500, null=True),
        ),
    ]
