# Generated by Django 5.0.2 on 2024-04-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_alter_staff_lab_comment_alter_student_lab_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other',
            name='lab_comment',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='registered_students',
            name='Balance',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='lab_comment',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
