# Generated by Django 5.0.2 on 2024-04-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_alter_other_lab_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='lab_comment',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
