# Generated by Django 5.0.2 on 2024-04-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_alter_staff_lab_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered_students',
            name='picture',
            field=models.ImageField(default=None, null=True, upload_to='static/profile_image/'),
        ),
    ]
