# Generated by Django 5.0.2 on 2024-04-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_registered_students_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='other',
            name='prescription',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='prescription',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='prescription',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
